
version: 2
jobs:

  build: # name of your job
    machine: # executor type
    # https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
      # image: ubuntu-2004:202010-01 # # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4
      image: ubuntu-1604:202007-01
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: "os fingerprinting"
          command: hostnamectl status                         
      - run:
          name: "build vagrant kvm libvirt"
          command: |
            sudo make deploy-libvirt
          environment:
            TERM: xterm-256color
            # sudo make deploy-vagrant
            # sudo make deploy-boxes  

